services:
  database:
    platform: linux/x86_64
    container_name: database
    image: mysql:8.0
    environment:
      - TZ=Asia/Seoul

    ports:
      - 3306:3306

    env_file: .env

  backend:
    container_name: backend
    restart: on-failure
    build:
      context: backend
      dockerfile: Dockerfile.dev

    entrypoint: ["pnpm", "run", "start:dev"]
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/backend/logs
    ports:
      - 3000:3000
    env_file: .env
