name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]

defaults:
  run:
    working-directory: backend

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pnpm 설치
        uses: pnpm/action-setup@v4
        with:
          version: 9
          package_json_file: "backend/package.json"

      - name: Node.js 22 설치
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: backend/pnpm-lock.yaml

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 린트
        run: pnpm lint

      - name: 포매팅
        run: pnpm format
        if: always()

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
