name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4

      - name: pnpm 설치
        uses: pnpm/action-setup@v4
        with:
          version: 9
          package_json_file: "backend/package.json"

      - name: Node.js ${{ matrix.node-version }} 설치
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: backend/pnpm-lock.yaml

      - name: 의존성 설치
        run: pnpm install

      - name: 테스트
        run: |
          pnpm lint:ci
          pnpm typecheck
          pnpm test:cov

      - name: Codecov에 커버리지 결과 배포
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
